FROM raspbian/stretch

RUN apt-get update \
    && apt-get -y install python3 \
    python3-pip \
    python3-dev \
    python3-rpi.gpio

RUN pip3 install RPi.GPIO
RUN pip3 install gpiozero
RUN pip3 install pika

COPY . .

CMD [ "python3", "./main.py" ]
